version: "3.9"

services:
  node1:
    build: .
    container_name: mom_node1
    ports:
      - "8001:8000"
      - "50051:50051"
    env_file:
      - .env.node1

  node2:
    build: .
    container_name: mom_node2
    ports:
      - "8002:8000"
      - "50052:50052"
    env_file:
      - .env.node2

  node3:
    build: .
    container_name: mom_node3
    ports:
      - "8003:8000"
      - "50053:50053"
    env_file:
      - .env.node3
