# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mom_server/grpc_services/messaging.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'mom_server/grpc_services/messaging.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(mom_server/grpc_services/messaging.proto\x12\tmessaging\"E\n\x0eMessageRequest\x12\x12\n\ntopic_name\x18\x01 \x01(\t\x12\x0e\n\x06sender\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\"!\n\x0fMessageResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2]\n\x10MessagingService\x12I\n\x10ReplicateMessage\x12\x19.messaging.MessageRequest\x1a\x1a.messaging.MessageResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mom_server.grpc_services.messaging_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MESSAGEREQUEST']._serialized_start=55
  _globals['_MESSAGEREQUEST']._serialized_end=124
  _globals['_MESSAGERESPONSE']._serialized_start=126
  _globals['_MESSAGERESPONSE']._serialized_end=159
  _globals['_MESSAGINGSERVICE']._serialized_start=161
  _globals['_MESSAGINGSERVICE']._serialized_end=254
# @@protoc_insertion_point(module_scope)
